[IG]
ig = fsh-generated/resources/ImplementationGuide-de.distance.pro.json
; MII-KDS-Template, wie in den Modul-Repos des MII Kerndatensatzes
template = https://github.com/medizininformatik-initiative/ig-template-mii-kds
