// Erzeugt von scripts/build_mapping.py aus mapping/distance-pro-mapping.csv – nicht von Hand bearbeiten.

Logical: DISTANCE_PRO_LM_Datensatz
Id: distance-pro-lm-datensatz
Title: "DISTANCE:PRO LM Datensatz"
Description: "Logisches Modell des Catalog of Items (CoI) der Studie DISTANCE:PRO, Version 1.1 vom 08.09.2026."
* identifikation 0..1 BackboneElement "Identifizierende Daten" "Identifizierende Daten"
  * name 0..1 HumanName "Name" "CoI-Item 1: Name (Relevanz: SONDER)"
  * geburtsdatum 0..1 date "Geburtsdatum" "CoI-Item 2: Geburtsdatum (Relevanz: SONDER)"
  * anschrift 0..1 Address "Anschrift" "CoI-Item 3: Anschrift (Relevanz: SONDER)"
  * telefon 0..1 ContactPoint "Telefon/Handynummer" "CoI-Item 4: Telefon/Handynummer (Relevanz: SONDER)"
  * fallnummer 0..1 Identifier "Fallnummer" "CoI-Item 5: Fallnummer (Relevanz: SONDER)"
  * patientenId 0..1 Identifier "Pat.-ID" "CoI-Item 6: Pat.-ID (Relevanz: SONDER)"
* person 0..1 BackboneElement "Patientenbezogene Daten" "Patientenbezogene Daten"
  * studienId 0..1 Identifier "Studien-ID" "CoI-Item 7: Studien-ID (Relevanz: MUSS)"
  * studienzentrum 0..1 Identifier "Studienzentrums-Nr" "CoI-Item 8: Studienzentrums-Nr (Relevanz: MUSS)"
  * groesse 0..1 Quantity "Größe" "CoI-Item 9: Größe (Relevanz: MUSS)"
  * gewicht 0..1 Quantity "Gewicht" "CoI-Item 10: Gewicht (Relevanz: MUSS)"
  * bmi 0..1 Quantity "BMI" "CoI-Item 11: BMI (Relevanz: berechnet)"
  * idealesGewicht 0..1 Quantity "Ideales Gewicht" "CoI-Item 12: Ideales Gewicht (Relevanz: berechnet)"
  * gewichtsverlust 0..1 Quantity "Gewichtsverlust" "CoI-Item 13: Gewichtsverlust (Relevanz: SOLL)"
  * alter 0..1 Quantity "Alter" "CoI-Item 14: Alter (Relevanz: MUSS)"
* soziodemographie 0..1 BackboneElement "Soziodemographische Daten" "Soziodemographische Daten"
  * lebenssituation 0..1 CodeableConcept "Lebenssituation" "CoI-Item 15: Lebenssituation (Relevanz: MUSS)"
  * wohnsituation 0..1 CodeableConcept "Wohnsituation" "CoI-Item 16: Wohnsituation (Relevanz: MUSS)"
  * hund 0..1 CodeableConcept "Hund" "CoI-Item 17: Hund (Relevanz: MUSS)"
  * sozialeUnterstuetzung 0..1 string "Unterstützung/soziales Umfeld" "CoI-Item 18: Unterstützung/soziales Umfeld (Relevanz: MUSS)"
  * raucher 0..1 CodeableConcept "Raucher" "CoI-Item 19: Raucher (Relevanz: MUSS)"
  * packYears 0..1 Quantity "Pack years" "CoI-Item 20: Pack years (Relevanz: MUSS)"
  * alkohol 0..1 CodeableConcept "Alkohol" "CoI-Item 21: Alkohol"
  * alkoholMenge 0..1 Quantity "Alkohol - wie viel?" "CoI-Item 22: Alkohol - wie viel?"
  * bildungsstand 0..1 CodeableConcept "Bildungsstand" "CoI-Item 23: Bildungsstand"
  * berufstaetigEinschluss 0..1 CodeableConcept "Berufstätig zum Einschlusszeitpunkt" "CoI-Item 24: Berufstätig zum Einschlusszeitpunkt"
* therapieverlauf 0..1 BackboneElement "Therapien im Verlauf" "Therapien im Verlauf"
  * chemotherapie 0..* Period "Chemotherapie" "CoI-Item 25: Chemotherapie (Relevanz: MUSS)"
  * immunsuppressiveTherapie 0..* Period "Immunsuppressive Therapie" "CoI-Item 26: Immunsuppressive Therapie (Relevanz: MUSS)"
  * strahlentherapie 0..* Period "Strahlentherapie" "CoI-Item 27: Strahlentherapie (Relevanz: MUSS)"
  * physiotherapie 0..* Period "Physiotherapie" "CoI-Item 28: Physiotherapie (Relevanz: MUSS)"
  * ergotherapie 0..* Period "Ergotherapie" "CoI-Item 29: Ergotherapie (Relevanz: MUSS)"
  * logopaedie 0..* Period "Logopädie" "CoI-Item 30: Logopädie (Relevanz: MUSS)"
  * rehabilitation 0..* CodeableConcept "Rehabilitationszentrum" "CoI-Item 31: Rehabilitationszentrum (Relevanz: MUSS)"
  * rehabilitationDauer 0..* Period "Dauer der Reha" "CoI-Item NEU-1: Dauer der Reha (Relevanz: SOLL)"
* verlauf 0..1 BackboneElement "Verlaufserhebung" "Verlaufserhebung"
  * berufstaetigkeitAktuell 0..* CodeableConcept "Aktuelle Berufstätigätigkeit" "CoI-Item 32: Aktuelle Berufstätigätigkeit (Relevanz: MUSS)"
  * karnofskyIndex 0..* CodeableConcept "Karnofsky Index" "CoI-Item 33: Karnofsky Index (Relevanz: MUSS)"
* fragebogen 0..1 BackboneElement "Fragebögen" "Fragebögen"
  * eortcQlqC30 0..* BackboneElement "EORT-QLQ-C30" "CoI-Item 34: EORT-QLQ-C30"
  * phq9 0..* BackboneElement "PHQ9" "CoI-Item 35: PHQ9"
  * gad7 0..* BackboneElement "GAD7" "CoI-Item 36: GAD7"
  * nrs 0..* integer "NRS" "CoI-Item 37: NRS"
  * kognition 0..* BackboneElement "Alternative für MOCA Test ??" "CoI-Item 38: Alternative für MOCA Test ??"
* diagnosen 0..1 BackboneElement "Diagnosen und Prozeduren" "Diagnosen und Prozeduren"
  * aufnahmediagnose 0..* CodeableConcept "Aufnahmediagnose" "CoI-Item 39: Aufnahmediagnose (Relevanz: MUSS)"
  * entlassdiagnose 0..* CodeableConcept "Entlassdiagnose" "CoI-Item 40: Entlassdiagnose (Relevanz: MUSS)"
  * nebendiagnosen 0..* CodeableConcept "Nebendiagnosen" "CoI-Item 41: Nebendiagnosen (Relevanz: MUSS)"
  * vorerkrankungen 0..* CodeableConcept "Vorerkrankungen" "CoI-Item 42: Vorerkrankungen (Relevanz: MUSS)"
  * operation 0..* CodeableConcept "OPS (OP-Prozeduren)" "CoI-Item 43: OPS (OP-Prozeduren) (Relevanz: MUSS)"
  * operationDatum 0..* dateTime "OP-Datum" "CoI-Item NEU-2: OP-Datum (Relevanz: MUSS)"
  * komplikationen 0..* CodeableConcept "Komplikationen" "CoI-Item NEU-3: Komplikationen (Relevanz: SOLL)"
  * chemotherapiePraeoperativ 0..* Period "Chemotherapie, präoperativ" "CoI-Item 44: Chemotherapie, präoperativ (Relevanz: MUSS)"
  * strahlentherapiePraeoperativ 0..* Period "Strahlentherapie, präoperativ" "CoI-Item 45: Strahlentherapie, präoperativ (Relevanz: MUSS)"
  * immuntherapiePraeoperativ 0..* Period "Immuntherapie, präoperativ" "CoI-Item 46: Immuntherapie, präoperativ (Relevanz: MUSS)"
* onkologie 0..1 BackboneElement "Onkologie" "Onkologie"
  * karnofskyIndex 0..* CodeableConcept "Karnofsky-Index" "CoI-Item 47: Karnofsky-Index (Relevanz: MUSS)"
  * ptnm 0..* CodeableConcept "pTNM" "CoI-Item 48: pTNM (Relevanz: MUSS)"
  * ecog 0..* CodeableConcept "ECOG-Score" "CoI-Item 49: ECOG-Score (Relevanz: MUSS)"
  * histologie 0..* CodeableConcept "Histologie" "CoI-Item 50: Histologie (Relevanz: MUSS)"
  * grading 0..* CodeableConcept "Grading" "CoI-Item 51: Grading (Relevanz: MUSS)"
* icuScores 0..1 BackboneElement "ICU-Scores" "ICU-Scores"
  * camIcu 0..* CodeableConcept "CAM-ICU" "CoI-Item 52: CAM-ICU (Relevanz: MUSS)"
  * rass 0..* CodeableConcept "RASS" "CoI-Item 53: RASS (Relevanz: MUSS)"
  * nrs 0..* integer "NRS" "CoI-Item 54: NRS (Relevanz: SOLL)"
  * sofa 0..* integer "SOFA Score" "CoI-Item 55: SOFA Score (Relevanz: MUSS)"
* anaesthesie 0..1 BackboneElement "Anästhesie und OP" "Anästhesie und OP"
  * asa 0..* CodeableConcept "ASA" "CoI-Item 56: ASA (Relevanz: SOLL)"
  * nyha 0..* CodeableConcept "NYHA" "CoI-Item 57: NYHA (Relevanz: SOLL)"
  * met 0..* Quantity "MET" "CoI-Item 58: MET (Relevanz: MUSS)"
  * opDauer 0..* Period "OP-Dauer" "CoI-Item 59: OP-Dauer (Relevanz: MUSS)"
  * blutverlust 0..* Quantity "Blutverlust" "CoI-Item 60: Blutverlust (Relevanz: SOLL)"
  * bluttransfusion 0..* CodeableConcept "Blutransfusion" "CoI-Item 61: Blutransfusion (Relevanz: KANN)"
* icuVerlauf 0..1 BackboneElement "ICU-Verlauf" "ICU-Verlauf"
  * katecholamintherapie 0..* Period "Katecholamintherapie" "CoI-Item 62: Katecholamintherapie (Relevanz: MUSS)"
  * beatmungsdauer 0..* Period "Beatmungsdauer" "CoI-Item 63: Beatmungsdauer (Relevanz: MUSS)"
  * beatmungsform 0..* CodeableConcept "Beatmungsform" "CoI-Item 64: Beatmungsform (Relevanz: SOLL)"
  * dialyse 0..* dateTime "Dialyse" "CoI-Item 65: Dialyse (Relevanz: MUSS)"
  * sedierung 0..* Period "Sedierung" "CoI-Item 66: Sedierung (Relevanz: SOLL)"
  * fluessigkeitsbilanz 0..* Quantity "24 Stunden Flüssigkeitsbilanz" "CoI-Item 67: 24 Stunden Flüssigkeitsbilanz (Relevanz: MUSS)"
  * extubation 0..* dateTime "Extubation" "CoI-Item 68: Extubation (Relevanz: MUSS)"
  * reintubation 0..* dateTime "Reintubation" "CoI-Item 69: Reintubation (Relevanz: SOLL)"
  * erstmobilisation 0..* dateTime "Erstmobilisation" "CoI-Item 70: Erstmobilisation (Relevanz: SOLL)"
  * kostaufbau 0..* dateTime "Beginn oraler Kostaufbau" "CoI-Item 71: Beginn oraler Kostaufbau (Relevanz: KANN)"
* vitaldaten 0..1 BackboneElement "Vitaldaten" "Vitaldaten"
  * herzfrequenz 0..* Quantity "Herzfrequenz (HF)" "CoI-Item 72: Herzfrequenz (HF)"
  * systolischerDruck 0..* Quantity "intraarterieller systolischer Druck (SAP)" "CoI-Item 73: intraarterieller systolischer Druck (SAP)"
  * mittlererDruck 0..* Quantity "mittlerer Arterieller Druck (MAP)" "CoI-Item 74: mittlerer Arterieller Druck (MAP)"
  * diastolischerDruck 0..* Quantity "diastolischer Druck (DAP)" "CoI-Item 75: diastolischer Druck (DAP)"
  * spo2 0..* Quantity "SpO2" "CoI-Item 76: SpO2"
* blutgasanalyse 0..1 BackboneElement "Blutgasanalyse" "Blutgasanalyse"
  * pao2 0..* Quantity "paO2" "CoI-Item 77: paO2"
  * paco2 0..* Quantity "PaCO2" "CoI-Item 78: PaCO2"
  * phArteriell 0..* Quantity "pH arteriell" "CoI-Item 79: pH arteriell"
  * sao2 0..* Quantity "SaO2" "CoI-Item 80: SaO2"
  * laktatArteriell 0..* Quantity "Laktat arteriell" "CoI-Item 81: Laktat arteriell"
  * bicarbonatArteriell 0..* Quantity "Bicarbonat arteriell" "CoI-Item 82: Bicarbonat arteriell"
  * svo2 0..* Quantity "SvO2" "CoI-Item 83: SvO2"
  * baseExcessArteriell 0..* Quantity "BE arteriell" "CoI-Item 84: BE arteriell"
* labor 0..1 BackboneElement "Laborwerte" "Laborwerte"
  * leukozyten 0..* Quantity "Leukozyten" "CoI-Item 85: Leukozyten"
  * thrombozyten 0..* Quantity "Thrombozyten" "CoI-Item 86: Thrombozyten"
  * haemoglobin 0..* Quantity "Hämoglobin" "CoI-Item 87: Hämoglobin"
  * haematokrit 0..* Quantity "Hämatokrit" "CoI-Item 88: Hämatokrit"
  * crp 0..* Quantity "CRP" "CoI-Item 89: CRP"
  * pct 0..* Quantity "PCT" "CoI-Item 90: PCT"
  * il6 0..* Quantity "IL-6" "CoI-Item 91: IL-6"
  * harnstoff 0..* Quantity "Harnstoff" "CoI-Item 92: Harnstoff"
  * kreatinin 0..* Quantity "Kreatinin" "CoI-Item 93: Kreatinin"
  * bilirubinGesamt 0..* Quantity "Bilirubin ges" "CoI-Item 94: Bilirubin ges"
  * albumin 0..* Quantity "Albumin" "CoI-Item 95: Albumin"
  * got 0..* Quantity "GOT" "CoI-Item 96: GOT"
  * gpt 0..* Quantity "GPT" "CoI-Item 97: GPT"
  * troponin 0..* Quantity "Troponin" "CoI-Item 98: Troponin"
  * ck 0..* Quantity "CK" "CoI-Item 99: CK"
  * ckMb 0..* Quantity "CKMB" "CoI-Item 100: CKMB"
  * ldh 0..* Quantity "LDH" "CoI-Item 101: LDH"
  * amylase 0..* Quantity "Amylase" "CoI-Item 102: Amylase"
  * lipase 0..* Quantity "Lipase" "CoI-Item 103: Lipase"
  * dDimere 0..* Quantity "D-Dimere" "CoI-Item 104: D-Dimere"
  * inr 0..* Quantity "INR" "CoI-Item 105: INR"
  * ptt 0..* Quantity "pTT" "CoI-Item 106: pTT"

Mapping: DISTANCE_PRO_LM_Datensatz_FHIR
Id: FHIR
Title: "Abbildung auf FHIR-Profile (MII KDS 2027)"
Source: DISTANCE_PRO_LM_Datensatz
Target: "http://hl7.org/fhir"
* identifikation.name -> "Patient.name:name" "MII PR Person Patient"
* identifikation.geburtsdatum -> "Patient.birthDate" "MII PR Person Patient, MII PR Person Patient (Pseudonymisiert)"
* identifikation.anschrift -> "Patient.address:Strassenanschrift" "MII PR Person Patient"
* identifikation.telefon -> "Patient.telecom" "MII PR Person Patient"
* identifikation.fallnummer -> "Encounter.identifier:Aufnahmenummer" "MII PR Fall Kontakt mit einer Gesundheitseinrichtung"
* identifikation.patientenId -> "Patient.identifier:pid; Patient.identifier:PseudonymisierterIdentifier" "MII PR Person Patient, MII PR Person Patient (Pseudonymisiert)"
* person.studienId -> "ResearchSubject.identifier:subjectIdentificationCode" "DISTANCE:PRO PR Proband"
* person.studienzentrum -> "ResearchSubject.extension:studienzentrum" "DISTANCE:PRO PR Proband"
* person.groesse -> "Observation.value[x]:valueQuantity" "MII PR ICU MUV Körpergröße"
* person.gewicht -> "Observation.value[x]:valueQuantity" "MII PR ICU MUV Körpergewicht"
* person.bmi -> "Observation.value[x]:valueQuantity" "DISTANCE:PRO PR BMI"
* person.idealesGewicht -> "Observation.value[x]" "SD MII ICU Ideales Körpergewicht (ISiK 6)"
* person.gewichtsverlust -> "Observation.value[x]:valueQuantity" "DISTANCE:PRO PR Gewichtsverlust"
* person.alter -> "Observation.value[x]:valueQuantity" "DISTANCE:PRO PR Alter bei Einschluss"
* soziodemographie.lebenssituation -> "Observation.value[x]:valueCodeableConcept" "DISTANCE:PRO PR Lebenssituation"
* soziodemographie.wohnsituation -> "Observation.value[x]:valueCodeableConcept" "DISTANCE:PRO PR Wohnsituation"
* soziodemographie.hund -> "Observation.value[x]:valueCodeableConcept" "DISTANCE:PRO PR Hundehaltung"
* soziodemographie.sozialeUnterstuetzung -> "Observation.value[x]:valueString" "DISTANCE:PRO PR Soziale Unterstützung"
* soziodemographie.raucher -> "Observation.value[x]:valueCodeableConcept" "MII PR Kardio Observation Rauchen"
* soziodemographie.packYears -> "Observation.component:packungsjahre" "MII PR Kardio Observation Rauchen"
* soziodemographie.alkohol -> "Observation.value[x]:valueCodeableConcept" "DISTANCE:PRO PR Alkoholkonsum"
* soziodemographie.alkoholMenge -> "Observation.component:reinalkohol; Observation.component:risikobewertung" "DISTANCE:PRO PR Alkoholkonsum"
* soziodemographie.bildungsstand -> "Observation.value[x]" "MII PR SDD Schulabschluss, MII PR SDD Ausbildung"
* soziodemographie.berufstaetigEinschluss -> "Observation.value[x]" "MII PR SDD Beschäftigungsstatus"
* therapieverlauf.chemotherapie -> "Procedure.performed[x]" "MII PR Onko Systemische Therapie"
* therapieverlauf.immunsuppressiveTherapie -> "MedicationStatement.effective[x]" "MII PR Medikation MedicationStatement"
* therapieverlauf.strahlentherapie -> "Procedure.performed[x]" "MII PR Onko Strahlentherapie"
* therapieverlauf.physiotherapie -> "Procedure.performed[x]" "DISTANCE:PRO PR Funktionelle Therapie"
* therapieverlauf.ergotherapie -> "Procedure.performed[x]" "DISTANCE:PRO PR Funktionelle Therapie"
* therapieverlauf.logopaedie -> "Procedure.performed[x]" "DISTANCE:PRO PR Funktionelle Therapie"
* therapieverlauf.rehabilitation -> "Encounter.class" "DISTANCE:PRO PR Rehabilitation"
* therapieverlauf.rehabilitationDauer -> "Encounter.period" "DISTANCE:PRO PR Rehabilitation"
* verlauf.berufstaetigkeitAktuell -> "Observation.value[x]" "MII PR SDD Beschäftigungsstatus"
* verlauf.karnofskyIndex -> "Observation.value[x]" "MII PR Onko Allgemeiner Leistungszustand Karnofsky"
* fragebogen.eortcQlqC30 -> "QuestionnaireResponse.item; Observation.value[x]" "MII PR PRO QuestionnaireResponse, MII PR PRO Score Instance"
* fragebogen.phq9 -> "QuestionnaireResponse.item; Observation.value[x]" "MII PR PRO QuestionnaireResponse, MII PR PRO Observation PHQ-9"
* fragebogen.gad7 -> "QuestionnaireResponse.item; Observation.value[x]" "MII PR PRO QuestionnaireResponse, MII PR PRO Score Instance"
* fragebogen.nrs -> "Observation.value[x]" "MII PR ICU Score Numerische Ratingskala"
* fragebogen.kognition -> "QuestionnaireResponse.item; Observation.value[x]" "MII PR PRO QuestionnaireResponse, MII PR PRO Score Instance"
* diagnosen.aufnahmediagnose -> "Condition.code; Encounter.diagnosis.use" "MII PR Diagnose Condition, MII PR Fall Kontakt mit einer Gesundheitseinrichtung"
* diagnosen.entlassdiagnose -> "Condition.code; Encounter.diagnosis.use" "MII PR Diagnose Condition, MII PR Fall Kontakt mit einer Gesundheitseinrichtung"
* diagnosen.nebendiagnosen -> "Condition.code; Encounter.diagnosis.use" "MII PR Diagnose Condition, MII PR Fall Kontakt mit einer Gesundheitseinrichtung"
* diagnosen.vorerkrankungen -> "Condition.code; Condition.onset[x]" "MII PR Diagnose Condition"
* diagnosen.operation -> "Procedure.code.coding:ops" "MII PR Prozedur Procedure, MII PR Onko Operation"
* diagnosen.operationDatum -> "Procedure.performed[x]" "MII PR Prozedur Procedure, MII PR Onko Operation"
* diagnosen.komplikationen -> "Procedure.complication" "MII PR Onko Operation, MII PR Prozedur Procedure"
* diagnosen.chemotherapiePraeoperativ -> "Procedure.performed[x]; Procedure.extension:StellungZurOp" "MII PR Onko Systemische Therapie"
* diagnosen.strahlentherapiePraeoperativ -> "Procedure.performed[x]; Procedure.extension:StellungZurOp" "MII PR Onko Strahlentherapie"
* diagnosen.immuntherapiePraeoperativ -> "Procedure.performed[x]; Procedure.extension:StellungZurOp; MedicationStatement.medication[x]" "MII PR Onko Systemische Therapie, MII PR Onko Systemische Therapie Medikation"
* onkologie.karnofskyIndex -> "Observation.value[x]" "MII PR Onko Allgemeiner Leistungszustand Karnofsky"
* onkologie.ptnm -> "Observation.value[x]; Observation.hasMember" "MII PR Onko TNM Klassifikation"
* onkologie.ecog -> "Observation.value[x]" "MII PR Onko Allgemeiner Leistungszustand ECOG"
* onkologie.histologie -> "Observation.value[x]; DiagnosticReport.conclusion" "MII PR Onko Histologie ICD-O-3, MII PR Patho Report"
* onkologie.grading -> "Observation.value[x]" "MII PR Onko Grading"
* icuScores.camIcu -> "Observation.value[x]:valueCodeableConcept" "MII PR ICU Score CAM-ICU"
* icuScores.rass -> "Observation.value[x]" "MII PR ICU Score RASS"
* icuScores.nrs -> "Observation.value[x]" "MII PR ICU Score Numerische Ratingskala"
* icuScores.sofa -> "Observation.value[x]:valueInteger" "MII PR ICU Score SOFA"
* anaesthesie.asa -> "Observation.value[x]" "MII PR Onko ASA Klassifikation"
* anaesthesie.nyha -> "Observation.value[x]" "MII PR Kardio Score NYHA"
* anaesthesie.met -> "Observation.value[x]:valueQuantity" "DISTANCE:PRO PR Metabolisches Äquivalent"
* anaesthesie.opDauer -> "Procedure.performed[x]:performedPeriod" "MII PR Prozedur Procedure"
* anaesthesie.blutverlust -> "Observation.value[x]" "MII PR ICU Bilanz Ausfuhr Blutverlust"
* anaesthesie.bluttransfusion -> "Procedure.code" "MII PR Prozedur Procedure"
* icuVerlauf.katecholamintherapie -> "MedicationAdministration.effective[x]; MedicationAdministration.medication[x]" "DISTANCE:PRO PR Katecholamintherapie"
* icuVerlauf.beatmungsdauer -> "Procedure.performed[x]:performedPeriod" "MII PR ICU Beatmung"
* icuVerlauf.beatmungsform -> "Procedure.code.coding:sct" "MII PR ICU Beatmung"
* icuVerlauf.dialyse -> "Procedure.performed[x]" "MII PR ICU Extrakorporales Verfahren"
* icuVerlauf.sedierung -> "MedicationAdministration.effective[x]; MedicationAdministration.medication[x]" "DISTANCE:PRO PR Sedierung"
* icuVerlauf.fluessigkeitsbilanz -> "Observation.value[x]" "MII PR ICU Bilanz Tagesbilanz Flüssigkeit"
* icuVerlauf.extubation -> "Procedure.performed[x]" "DISTANCE:PRO PR Postoperatives Ereignis"
* icuVerlauf.reintubation -> "Procedure.performed[x]" "DISTANCE:PRO PR Postoperatives Ereignis"
* icuVerlauf.erstmobilisation -> "Procedure.performed[x]" "DISTANCE:PRO PR Postoperatives Ereignis"
* icuVerlauf.kostaufbau -> "Procedure.performed[x]" "DISTANCE:PRO PR Postoperatives Ereignis"
* vitaldaten.herzfrequenz -> "Observation.value[x]" "MII PR ICU MUV Herzfrequenz"
* vitaldaten.systolischerDruck -> "Observation.component:SystolicBP" "MII PR ICU MUV Arterieller Blutdruck"
* vitaldaten.mittlererDruck -> "Observation.component:meanBP" "MII PR ICU MUV Arterieller Blutdruck"
* vitaldaten.diastolischerDruck -> "Observation.component:DiastolicBP" "MII PR ICU MUV Arterieller Blutdruck"
* vitaldaten.spo2 -> "Observation.value[x]" "SD MII ICU Sauerstoffsättigung im arteriellen Blut durch Pulsoxymetrie (ISiK 6)"
* blutgasanalyse.pao2 -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.paco2 -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.phArteriell -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.sao2 -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.laktatArteriell -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.bicarbonatArteriell -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.svo2 -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* blutgasanalyse.baseExcessArteriell -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.leukozyten -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.thrombozyten -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.haemoglobin -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.haematokrit -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.crp -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.pct -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.il6 -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.harnstoff -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.kreatinin -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.bilirubinGesamt -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.albumin -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.got -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.gpt -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.troponin -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.ck -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.ckMb -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.ldh -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.amylase -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.lipase -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.dDimere -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.inr -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
* labor.ptt -> "Observation.value[x]" "DISTANCE:PRO PR Laboruntersuchung"
